### ISSUE TITLE
Bug at line 161 in HashTab.cpp that required an extra user input, and error in main print statement

### ISSUE THREAD

**Issue by LoganConnor** [purpledonut/Chadly_CSCI2270_FinalProject#3]
Overall this is a great project, and solid code! I like the functionality that you built on top of assignment 9. Congratulations! The first comment I have is that average table depth is not really a meaningful metric below a certain number of words. For instance, with a table size of 20 and 1 word inserted an average depth of 0.05 per slot is odd. Second, per my pull request, there was a bug in line 161 of the HashTab.cpp where the user has to enter something after calling #12 from the menu before they can return to the menu. Also, line #44 in the main should have said 1-4 but said 1-10, so I changed that too. Great work!

**Comment by duncanchadly** [comment]
Thanks, I merged all changes! Glad you liked the project.
